<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.curly</string>
	</array>
	<key>name</key>
	<string>Curly Template</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)\{\{!</string>
			<key>end</key>
			<string>\}\}</string>
			<key>name</key>
			<string>comment.block.curly</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)(\{\{)(/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.curly</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.terminate.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.curly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.terminate.curly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#terminateTag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)(\{\{)(#)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.curly</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.if.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.curly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.if.curly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)(\{\{)(\^)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.curly</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.unless.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.curly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.unless.curly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)(\{\{)(\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.curly</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.collection.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.curly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.collection.curly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)(\{\{)(@)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.curly</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.context.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\}\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.curly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.context.curly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\{)\{\{(?!\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin.curly</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.control.end.curly</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.basic.curly</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>tag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#terminateTag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>keyword.operator.argument-seperator.curly</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.curly</string>
				</dict>
				<dict>
					<key>match</key>
					<string>"[^"]*"</string>
					<key>name</key>
					<string>string.quoted.double.curly</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'[^']*'</string>
					<key>name</key>
					<string>string.quoted.single.curly</string>
				</dict>
			</array>
		</dict>
		<key>terminateTag</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([a-z_][a-zA-Z_0-9]*[?!]?)</string>
					<key>name</key>
					<string>variable.other.curly</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.curly</string>
	<key>uuid</key>
	<string>c86979be-c965-4918-ba0e-0eac4a04db49</string>
</dict>
</plist>
